import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/navBar";
import { Providers } from "@/Redux/provider";
import { UseAppSelector } from "@/Redux/store";
import { getTokenCookies } from "@/helper/cookies";
import ThemeProvider from "./components/themeProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EX.NEXT MUI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ThemeProvider>
            {getTokenCookies() ? <Navbar /> : null}
            {children}
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
